### ISSUE TITLE
'make' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by BenjaminNeilDavis** [jasaw/bbPiCam#1]
I am having issues with both Load environment variables: and 'make'. I have tried to research what the issue is but cannot find it. What am I doing wrong? Thanks

**Comment by jasaw** [comment]
Try installing 'make' on your build machine. If you're running make on a Raspbian, try running 'sudo apt-get install build-essential' first.
If you already have 'make' installed, make sure you have it in your PATH environment variable.

As for the 'Load environment variables', you have to edit the build_env file to point to your own directory structure. What error message are you getting at this step?
